defmodule MazaoDaktariWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :mazao_daktari

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_mazao_daktari_key",
    signing_salt: "MexvRD6i",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :mazao_daktari,
    gzip: not code_reloading?,
    only: MazaoDaktariWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # CORSPlug's init/1 bakes `origin:` in at compile time (standard Plug
  # behavior), so it must come from literal Application config
  # (`config :cors_plug, origin: [...]` in dev.exs/prod.exs), not a runtime
  # env var lookup or an MFA tuple passed here.
  plug CORSPlug

  plug MazaoDaktariWeb.Router
end
