export type Language = "en" | "sw";

export const STRINGS: Record<Language, Record<string, string>> = {
  en: {
    tagline: "Snap a photo, get advice.",
    heroTitle: "Diagnose your crop in seconds",
    heroSubtitle:
      "Photograph a sick plant or describe the problem — get a clear diagnosis and treatment steps in English or Swahili, free.",
    stepPhoto: "Photograph",
    stepDiagnose: "Diagnose",
    stepTreat: "Treat",
    howItWorks: "How it works",
    labelDesc: "Describe the problem (optional)",
    labelPhoto: "Add a photo of the crop",
    uploadPrompt: "Tap to add a photo",
    removePhoto: "Remove photo",
    placeholder: "e.g. Yellow spots on maize leaves, started this week",
    hint: "Works with just a description if you can't take a photo. Data used only for this diagnosis.",
    submit: "Diagnose",
    submitting: "Diagnosing...",
    tSymptoms: "Symptoms matched",
    tTreatment: "Treatment",
    tPrevention: "Prevention",
    needInput: "Provide a photo, a description, or both.",
    failed: "Something went wrong. Try again.",
    mockNote:
      "Demo mode: this is a sample diagnosis, not a live AI call. Set GEMINI_API_KEYS on the server for real results.",
    signedInAs: "Signed in as",
    signIn: "Sign in",
    signOut: "Sign out",
    signInHint: "Sign in to save your diagnosis history",
    signInFailed: "Google sign-in failed. Try again.",
    history: "History",
    hideHistory: "Hide history",
    noHistory: "No past diagnoses yet.",
    loadingHistory: "Loading history...",
    footer: "Built for GoMyCode “Come Build with AI” — Mazao Daktari",
  },
  sw: {
    tagline: "Piga picha, pata ushauri.",
    heroTitle: "Chunguza zao lako kwa sekunde",
    heroSubtitle:
      "Piga picha ya mmea mgonjwa au eleza tatizo — pata uchunguzi wazi na hatua za tiba kwa Kiingereza au Kiswahili, bure.",
    stepPhoto: "Piga picha",
    stepDiagnose: "Chunguza",
    stepTreat: "Tibu",
    howItWorks: "Jinsi inavyofanya kazi",
    labelDesc: "Eleza tatizo (si lazima)",
    labelPhoto: "Ongeza picha ya zao",
    uploadPrompt: "Gusa kuongeza picha",
    removePhoto: "Ondoa picha",
    placeholder: "mfano: Madoa ya njano kwenye majani ya mahindi, yalianza wiki hii",
    hint: "Inafanya kazi kwa maelezo tu ukikosa picha. Data hutumika kwa uchunguzi huu tu.",
    submit: "Chunguza",
    submitting: "Inachunguza...",
    tSymptoms: "Dalili zinazofanana",
    tTreatment: "Tiba",
    tPrevention: "Kinga",
    needInput: "Weka picha, maelezo, au vyote viwili.",
    failed: "Hitilafu imetokea. Jaribu tena.",
    mockNote:
      "Hali ya majaribio: hii ni mfano wa uchunguzi, si wito wa moja kwa moja wa AI. Weka GEMINI_API_KEYS kwenye seva kwa matokeo halisi.",
    signedInAs: "Umeingia kama",
    signIn: "Ingia",
    signOut: "Toka",
    signInHint: "Ingia ili kuhifadhi historia ya uchunguzi wako",
    signInFailed: "Kuingia kwa Google kumeshindikana. Jaribu tena.",
    history: "Historia",
    hideHistory: "Ficha historia",
    noHistory: "Hakuna uchunguzi wa awali bado.",
    loadingHistory: "Inapakia historia...",
    footer: "Imejengwa kwa ajili ya GoMyCode “Come Build with AI” — Mazao Daktari",
  },
};
